### ISSUE TITLE
Resize image inside CK Editor

### ISSUE THREAD

**Issue by kaspar-allenbach** [katrinkerber/statamic-ckeditor#5]
Hi Katrin.

Is it somehow possible to add the redactor resizing option in ckeditor:

```
resize:
    width: 500
    height: 300
    quality: 60
    upsize: false
```

That would be awesome.
